# Generated by Django 5.0.3 on 2024-03-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
