# Generated by Django 5.0.3 on 2024-03-10 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
