# Generated by Django 5.0.3 on 2024-03-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': '배송지 주소'},
        ),
    ]
